version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=mikrotik_manager_db
      - POSTGRES_USER=mikrotik_user
      - POSTGRES_PASSWORD=mikrotik_password

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  backend:
    build: ../backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=mikrotik_manager_backend.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis

    celery_worker:
    build:
      context: ../backend  # Onde o código-fonte do backend está
      dockerfile: ./backend.Dockerfile # Onde o Dockerfile do backend está, relativo a este docker-compose.yml
    command: celery -A mikrotik_manager_backend worker -l info
    volumes:
      - ../backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=mikrotik_manager_backend.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - db


  frontend:
    build:
      context: ../frontend  # Onde o código-fonte do frontend está
      dockerfile: ./frontend.Dockerfile # Onde o Dockerfile do frontend está, relativo a este docker-compose.yml
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:


